/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Erdős Problem 1066

*Reference:* [erdosproblems.com/1066](https://www.erdosproblems.com/1066)

Let $G$ be a graph given by $n$ points in $\mathbb{R}^2$, where any two distinct points are
at least distance $1$ apart, and we draw an edge between two points if they are
distance $1$ apart.

Let $g(n)$ be maximal such that any such graph always has an independent set on
at least $g(n)$ vertices. Estimate $g(n)$, or perhaps $\lim g(n)/n$.

Such graphs are always planar. The current record bounds are
$$\frac{8}{31}n \leq g(n) \leq \frac{5}{16}n.$$
The lower bound is due to Swanepoel [Sw02] and the upper bound to Pach and
Tóth [PaTo96].

[Sw02] Swanepoel, K., *Unit distances and diameters in Euclidean spaces*.
Discrete & Computational Geometry 28 (2002), 351-370.

[PaTo96] Pach, J. and Tóth, G., *How many unit equilateral triangles can be
generated by n points in convex position?* (1996).
-/

namespace Erdos1066

/--
**Erdős Problem 1066**, lower bound [Sw02]:

For every $n \geq 1$ and every injective placement of $n$ points in $\mathbb{R}^2$ with all
pairwise distances $\geq 1$, there exists a set of at least $\frac{8}{31}n$ points with
no two at distance exactly $1$ (an independent set in the unit distance graph).
-/
@[category research solved, AMS 5 52]
theorem erdos_1066 (n : ℕ) (hn : n ≥ 1)
    (f : Fin n → EuclideanSpace ℝ (Fin 2))
    (hf_inj : Function.Injective f)
    (hf_min : ∀ i j : Fin n, i ≠ j → dist (f i) (f j) ≥ 1) :
    ∃ S : Finset (Fin n),
      (S.card : ℝ) ≥ 8 / 31 * (n : ℝ) ∧
      ∀ i ∈ S, ∀ j ∈ S, i ≠ j → dist (f i) (f j) ≠ 1 := by
  sorry

/--
**Erdős Problem 1066**, upper bound [PaTo96]:

For all sufficiently large $n$, there exists an injective placement of $n$ points
in $\mathbb{R}^2$ with all pairwise distances $\geq 1$ such that every independent set in the
unit distance graph has size at most $\frac{5}{16}n$.
-/
@[category research solved, AMS 5 52]
theorem erdos_1066.variants.upper_bound :
    ∃ N₀ : ℕ, ∀ n : ℕ, n ≥ N₀ →
      ∃ f : Fin n → EuclideanSpace ℝ (Fin 2),
        Function.Injective f ∧
        (∀ i j : Fin n, i ≠ j → dist (f i) (f j) ≥ 1) ∧
        ∀ S : Finset (Fin n),
          (∀ i ∈ S, ∀ j ∈ S, i ≠ j → dist (f i) (f j) ≠ 1) →
          (S.card : ℝ) ≤ 5 / 16 * (n : ℝ) := by
  sorry

end Erdos1066
